name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: app-personas-docker

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v4

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir, Etiquetar y Subir imagen a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        echo "Construyendo la imagen..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        echo "Subiendo la imagen a ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar en servidor EC2 por SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: ECR_REGISTRY,AWS_REGION
        script: |
          export PATH=$PATH:/usr/bin:/usr/local/bin:/snap/bin
          echo "Iniciando sesión en ECR desde EC2..."
          /usr/bin/aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
          
          echo "Deteniendo el contenedor viejo..."
          sudo docker stop servidor_web || true
          sudo docker rm servidor_web || true
          
          echo "Descargando la nueva imagen..."
          sudo docker pull $ECR_REGISTRY/app-personas-docker:latest
          
          echo "Iniciando el nuevo contenedor..."
          sudo docker run -d -p 3000:3000 --name servidor_web $ECR_REGISTRY/app-personas-docker:latest
